title: CMI Chameleons - VEX IQ Elementary School Team
author: pengthom
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  VEX IQ Robotics Team 47764A
# social links
twitter_username: dc_robots
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-dinky
